spring:
  application:
    name: rewards-service
server:
  port: 8102
management:
  endpoints:
    web:
      exposure:
        include: health,info

rewards:
  data:
    base-url: http://localhost:8101
    batch-size: 50
  poll:
    ms: 5000
