server:
  port: 8112

crowdsourced:
  baseUrl: http://localhost:8111

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

rewards:
  badges:
    - name: Gold
      threshold: 1000
    - name: Silver
      threshold: 500
    - name: Bronze
      threshold: 100


