spring.application.name=rewards-service
server.port=8122
crowdsourced-data.base-url=http://localhost:8121
rewards.refresh-interval-ms=60000

# Actuator Configuration (Health checks)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
