server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/waterquality
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized


