server:
  port: 8080

services:
  crowdsourced:
    baseUrl: http://localhost:8081
  rewards:
    baseUrl: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info


